<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Mermaid.js</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Handle Comments</string>
			<key>match</key>
			<string>%%.*</string>
			<key>name</key>
			<string>comment.mermaid</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Directive Boundaries</string>
			<key>match</key>
			<string>(%%\\{|\\}%%)</string>
			<key>name</key>
			<string>meta.preprocessor.mermaid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.directive.key.mermaid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keys and Structures in Directives</string>
			<key>match</key>
			<string>\b([A-Za-z_][A-Za-z0-9_]*)\b\s*(:|\{|\})</string>
			<key>name</key>
			<string>entity.name.function.mermaid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.key.mermaid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.value.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Quoted Key-Value Pairs</string>
			<key>match</key>
			<string>'([^']*)'\s*:\s*('([^']*)'|true|false|\d+)</string>
			<key>name</key>
			<string>constant.language.mermaid</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[|\(|\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.shape.begin.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Node Shapes</string>
			<key>end</key>
			<string>(\]|\)|\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.shape.end.mermaid</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.node.shape.mermaid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^\[\]\(\)\{\}]+</string>
					<key>name</key>
					<string>entity.name.type.mermaid</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.node.mermaid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.shape.end.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Special Case for Odd Shapes</string>
			<key>match</key>
			<string>([a-zA-Z0-9_]+&gt;)[^\[\]\(\)\{\}]*?(\])</string>
			<key>name</key>
			<string>entity.name.type.mermaid</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(graph|flowchart|subgraph|end|class|classDef|state|section|title)\b</string>
			<key>name</key>
			<string>keyword.control.mermaid</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Link Operators</string>
			<key>match</key>
			<string>(--+&gt;|==+&gt;|-\.-&gt;|--+|-\.+-|==+)</string>
			<key>name</key>
			<string>keyword.operator.js.mermaid</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.begin.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Link Labels</string>
			<key>end</key>
			<string>\|</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.end.mermaid</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.link.label.mermaid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^|]+</string>
					<key>name</key>
					<string>string.mermaid</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multi-line Text in Quotes</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mermaid</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mermaid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^"]+</string>
					<key>name</key>
					<string>string.quoted.double.mermaid</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.subgraph.mermaid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Regex for Capturing Subgraph Names</string>
			<key>match</key>
			<string>\bsubgraph\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>entity.name.function.mermaid</string>
		</dict>
	</array>
  <key>uuid</key>
          <string>6034E102-B645-4C6B-9C1D-520FF51BBE47</string>
  	<key>scopeName</key>
  	<string>source.mermaid</string>
  </dict>
  </plist>